test_shell/test_shell.h, test_shell/test_shell.vcxproj, test_shell/test_shell.vcxproj.filters
jw.song(chokosal)
test shell module을 위한 test_shell.cpp와 test_shell.h파일을 추가했습니다.
어떤 변경 사항이 있나요?
없습니다.
=> [feature] add Test TestShellFile.cpp/.h

test_shell/mock_ssd_adapter.h, test_shell/ssd_interface.h
#jwon96park #shin-son #chokosal #Limdongguen
Adapter 를 사용하기 위한 interface 및 TDD 를 위한 mock 생성
어떤 변경 사항이 있나요?
=> [feat] ssd interface & mock adapter

test_shell/main.cpp, test_shell/mock_ssd_adapter.h, test_shell/ssd_interface.h, test_shell/test_shell.vcxproj, test_shell/test_shell.vcxproj.filters
#jwon96park #shin-son #chokosal #Limdongguen
mock 을 사용하기 위해 gmock 헤더 선언하는 부분을 추가해주었고, class 안에서 public: 을 선언해주었습니다.
추가로, 헤더파일이 visual studio 의 프로젝트 항목에서 안보이는 문제가 있었는데, test_shell/test_shell.vcxproj.filters 에 헤더 파일 항목을 추가해줌으로써 해결해주었습니다.
어떤 변경 사항이 있나요?
=> [fix] add public declaration & add header files

test_shell/main.cpp, test_shell/test_shell.cpp, test_shell/test_shell.h
#jwon96park #shin-son #chokosal #Limdongguen
runCommand를 main에서 TestShell로 위치를 변경하고 runShell로 함수명을 변경하였습니다.
exit과 help에 대한 간단한 실행 코드를 추가하였습니다.
어떤 변경 사항이 있나요?
printHelp 함수에 각자 개발하시는 기능에 대한 설명을 추가해주시면 감사하겠습니다.
=> [FEATURE] Add exit and help

test_shell/main.cpp, test_shell/main_test.cpp, test_shell/test_shell.vcxproj, test_shell/test_shell.vcxproj.filters
#jwon96park #shin-son #chokosal #Limdongguen
gtest 에서 실행할 Test 를 모아둔 main_test.cpp 를 추가하였습니다.
어떤 변경 사항이 있나요?
=> [feat] add main_test.cpp

test_shell/test_shell.h
=> [fix] edit variable name

test_shell/main_test.cpp, test_shell/test_shell.cpp, test_shell/test_shell.h
#Limdongguen
fullWriteAndReadCompare 함수 추가 및 유닛테스트 추가하였습니다.
리팩토링은 PR을 나눠서 추후 진행예정입니다.
어떤 변경 사항이 있나요?
=> [feature] add fullWriteAndReadCompare

test_shell/main_test.cpp, test_shell/test_shell.cpp
송재원
최초 명세에 있는 Invalid command 처리를 TC와 함께 추가했습니다.
어떤 변경 사항이 있나요?
없음
=> [feature] invalid command handling 및 TC 추가

test_shell/test_shell.cpp
#손신
WriteReadAging 에 대한 help script 추가하였습니다.
어떤 변경 사항이 있나요?
=> [feat] writeReadAging: Add help description

test_shell/mock_ssd_adapter.h, test_shell/ssd_adapter.cpp, test_shell/ssd_adapter.h, test_shell/ssd_interface.h
송재원
erase 및 erase_range를 위해 반드시 필요한 기능으로 interface에 추가하여 adapter구현이 필요합니다.
어떤 변경 사항이 있나요?
@Limdongguen 님, SsdAdapter에는 일단 빌드를 위해 빈 함수로 추가해두었습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> [feature] SSDInterface에 erase 추가

ssd/Ssd_Read.cpp, ssd/main.cpp, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, ssd/ssd_constants.h, ssd/ssd_erase.cpp, ssd/ssd_erase.h, ssd/ssd_facade.cpp, ssd/ssd_facade.h, ssd/ssd_file_io.cpp, ssd/ssd_file_io.h, ssd/ssd_read_test.cpp
김성민
ssd 에서 erase 하는 기능 구현했습니다.
예외 처리는 pattern_checker 에서 추가 구현 예정입니다.
file 읽고 쓰는 기능을 하는 file io class 를 구현했습니다.
기타 네이밍룰에 맞게 파일명 수정했습니다.
어떤 변경 사항이 있나요?
read / write / erase 에서 공통 코드로 file 입출력 코드가 있어서
erase 에 먼저 file io class 를 사용한 코드로 구현했습니다.
추후 read / write 에서도 file io class 를 사용해서 중복코드가 없도록 수정 할 예정입니다.
=> ssd erase 기능 구현

test_shell/ssd_adapter.cpp, test_shell/test_shell.cpp
#임동균
1. exe 테스트를 위해서 경로와 테스트 수정했습니다. (ssd 폴더에서 실행해야 합니다.)
예시 - fkiller_ssd_project/ssd  경로에서 $ ../x64/Release/test_shell.exe 실행
2. 1_ 과 2_ 테스트에서 string compare로 변경하였습니다.
3. fullwrite command 기능 사용을 위한 command 추가
어떤 변경 사항이 있나요?
=> [fix] Testshell.exe Test fix

test_shell/main_test.cpp, test_shell/ssd_adapter.cpp, test_shell/test_shell.cpp
#임동균
Release 와 Debug 테스트에서 실패하는 케이스를 찾아서 고쳤고
SSD 업데이트에서 적용된 줄바뀜 문자를 adapter에서 제거하여 가져와서
테스트 에러를 제거했습니다.
어떤 변경 사항이 있나요?
=> [fix] fix adapter and test_shell for Test

test_shell/constants.h, test_shell/main_test.cpp, test_shell/test_shell.cpp, test_shell/test_shell.h
송재원
1. EraseAndWriteAging기능추가
2. Erase관련 help 추가
3. 일부 fail되는 TC를 pass 되도록 수정
어떤 변경 사항이 있나요?
=> [feature] Script4 - EraseAndWriteAging 기능추가

test_shell/main_test.cpp, test_shell/test_shell.cpp
#박종원
read fullread 의 출력을 요구사항에 맞게 수정하였습니다.
어떤 변경 사항이 있나요?
포맷을 변경해줌에 따라 테스트 결과 값이 달라지게 되어 TC 도 수정을 해주게 되었습니다.
참고 부탁드립니다.
=> [fix] modify read print format

ssd/buffer_command_test.cpp, ssd/command_process.h, ssd/commnad_process.cpp, ssd/commnad_process_test.cpp, ssd/main.cpp, ssd/ssd_constants.h
김성민
command processor class 에 build pattern 적용했습니다.
어떤 변경 사항이 있나요?
패턴 적용 확인 부탁드립니다.
=> [refactoring] apply build pattern at command processor class

ssd/buffer_command_test.cpp, ssd/buffer_manager.cpp, ssd/buffer_manager.h, ssd/command_process.h, ssd/main.cpp, ssd/ssd_facade.cpp, ssd/ssd_facade.h
김성민
buffer manager 내부에서 동작해야하는 코드 위치 수정했습니다.
fasade 패턴에 맞게 run 함수 지웠습니다.
어떤 변경 사항이 있나요?
=> buffer manager code 정리 / fasade code 정리

ssd/buffer_command_test.cpp, ssd/buffer_manager.cpp, ssd/buffer_manager.h
#임동균
buffer write 구현했습니다.
write 가 들어왔을떄 버퍼의 erase 바운더리인지 체크하고 그러면 앞의 erase의 바운더리를 바꾸거나
만약 필요없는 erase면 삭제하는 코드를 추가하였습니다.
어떤 변경 사항이 있나요?
=> [feature] Add buffer write

test_shell/test_shell.cpp
#임동균
fix erase range check
어떤 변경 사항이 있나요?
=> [fix] fix erase range check

ssd/buffer_manager.cpp, ssd/buffer_manager.h, ssd/command_process.h, ssd/main.cpp, ssd/pattern_checker.cpp, ssd/pattern_checker.h, ssd/ssd.vcxproj, ssd/ssd.vcxproj.filters, ssd/ssd_constants.h, ssd/ssd_initial_files.cpp, ssd/ssd_initial_files.h
송형주
맨 처음 버퍼 폴더 없으면 만들어주는 코드 추가
어떤 변경 사항이 있나요?
=> 버퍼 폴더 만들고, 버퍼 만들어주기

ssd/buffer_manager.cpp, ssd/buffer_manager.h, ssd/main.cpp, test_shell/ssd_adapter.cpp
#임동균
adapter에 erase 기능을 추가하였습니다.
어떤 변경 사항이 있나요?
=> Add erase adapter

ssd/pattern_checker.cpp, ssd/ssd_constants.h
김성민
erase 범위 체크 에러 수정
e 99 1 일 경우 되지 않던 문제 수정
어떤 변경 사항이 있나요?
=> [fix] erase arrange check bug fix

ssd/ssd_load_file.cpp, ssd/ssd_load_file.h
#임동균
getSsdNandData 의 리턴을 주소값으로 받아오게 변경
어떤 변경 사항이 있나요?
=> [fix] fix getSsdNandData

test_shell/erase_range_command.cpp
송재원
Erase range와 erase의 help파일이 동일해서 수정
어떤 변경 사항이 있나요?
=> [fix] erase_range의 help message 오류 수정

ssd/buffer_command_test.cpp, ssd/buffer_manager.cpp
#박종원
erase 할 때 range boundary 체크 코드에 버그가 있어 수정
어떤 변경 사항이 있나요?
=> [fix] erase
